server:
  port: 8080

spring:
  profiles:
    include: secret_key
  application:
    name: msa-gateway
  cloud:
    gateway:
      routes:
        - id: msa-auth-servce
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: msa-user-servce
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**
          filters:
            - CustomAuthFilter
            - RewritePath=/user-service/?(?<segment>.*), /$\{segment}

        - id: msa-board-servce
          uri: http://localhost:8083
          predicates:
            - Path=/board-service/**
          filters:
            - CustomAuthFilter
            - RewritePath=/board-service/?(?<segment>.*), /$\{segment}

        - id: msa-reply-servce
          uri: http://localhost:8084
          predicates:
            - Path=/reply-service/**
          filters:
            - CustomAuthFilter
            - RewritePath=/reply-service/?(?<segment>.*), /$\{segment}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
