server:
  port: 8080

spring:
  profiles:
    include: secret_key
  application:
    name: msa-gateway
  cloud:
    gateway:
      routes:
        - id: msa-auth-servce
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: msa-user-servce
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters:
            - CustomAuthFilter

        - id: msa-board-servce
          uri: http://localhost:8083
          predicates:
            - Path=/board/**
          filters:
            - CustomAuthFilter

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
